name: Publish Windows

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on                             
    steps:
    - name: Checkout MarsUndiscovered
      uses: actions/checkout@v3
      with:
        repository: DavidFidge/MarsUndiscovered
        path: MarsUndiscovered
        
    - name: Checkout FrigidRogue
      uses: actions/checkout@v3
      with:
        repository: DavidFidge/FrigidRogue
        path: FrigidRogue
        
    - name: Checkout GoRogue
      uses: actions/checkout@v3
      with:
        repository: DavidFidge/GoRogue
        ref: FrigidRogue
        path: GoRogue

    - name: Checkout GeonBit.UI
      uses: actions/checkout@v3
      with:
        repository: DavidFidge/GeonBit.UI
        ref: FrigidRogue
        path: GeonBit.UI
        
    - name: Checkout BehaviourTree
      uses: actions/checkout@v3
      with:
        repository: DavidFidge/BehaviourTree
        path: BehaviourTree

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2     

    - name: Build and Publish
      run: |
        dotnet publish .\MarsUndiscovered\MarsUndiscovered\MarsUndiscovered.csproj /p:UseAppHost=true /p:TieredCompilation=false /p:DebugType=None /p:DebugSymbols=false --self-contained --configuration Release --runtime win-x64 --output Publish --framework net6.0-windows
      
    - name: Create Artifact
      run: |
        7z a .\MarsUndiscovered-windows-x86_64.zip .\Publish\*

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: windows-x86_64
        path: MarsUndiscovered-windows-x86_64.zip
